### ISSUE TITLE
Agent run does not populate ocs server database

### ISSUE THREAD

**Issue by p-saimbhi** [PluginsOCSInventory-NG/vmware-vcenter#11]
No error on running the agent or in httpd logs but vm list and all vmware plugin information is empty.  I am using version 2.6 server and agent.

**Comment by 0XD1B** [comment]
Hello, did you find a way to fix this problem @p-saimbhi ? I have the same issue :cry:

**Comment by woulf** [comment]
Same problem here, tables have been created but are empty after a successful scan

**Comment by woulf** [comment]
Ok go it working, don't know what was actually needed:

- install libsoap-lite-perl
-  mkdir /etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins/Vmware_Vcenter/
- cp /usr/share/ocsinventory-reports/ocsreports/extensions/vmware_vcenter/APACHE/Map.pm /etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins/Vmware_Vcenter/
-  cp /usr/share/ocsinventory-reports/ocsreports/extensions/vmware_vcenter/APACHE/vmware_vcenter.conf /etc/ocsinventory-server/plugins/
- chown www-data:www-data /etc/ocsinventory-server/perl/Apache/Ocsinventory/Plugins/Vmware_Vcenter/Map.pm 
- chown www-data:www-data /etc/ocsinventory-server/plugins/vmware_vcenter.conf
- systemctl reload apache2

**Comment by 0XD1B** [comment]
Yeah i've got it running aswell since my previous message. I should have write down here the alternative that worked me though, my bad.
Same as @woulf i had to do the same steps except the libsoap-lite-perl install. (i didn't installed it).

The documentation lacks information about that mapping part between the XML pushed by the agent and the server.

**Comment by p-saimbhi** [comment]
Thanks woulf.  It also worked on RHEL 7.7
